spring.data.mongodb.uri=${MONGODB_URI} 
#Refer to Environmental variables for the URI

spring.data.mongodb.database=journaldb

#This below command enables indexing to work automatically
spring.data.mongodb.auto-index-creation=true 

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword