spring.data.mongodb.uri=mongodb+srv://smashroff_db_user:IBn7MmgJUlwMIYar@cluster0.1jpuped.mongodb.net/?appName=Cluster0

spring.data.mongodb.database=journaldb

#This below command enables indexing to work automatically
spring.data.mongodb.auto-index-creation=true 

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword